### ISSUE TITLE
(pandoc) installation error

### ISSUE THREAD

**Issue by pyhedgehog** [majkinetor/au-packages#91]
## Expected Behavior
`choco install pandoc` should install without error

## Current Behavior
`choco install pandoc` shows error `ERROR: Cannot bind argument to parameter 'Path' because it is null.`

relevant Log entries show:
```
2018-06-27 17:46:33,808 3680 [DEBUG] - Running Install-ChocolateyInstallPackage -packageName 'pandoc' -fileType 'msi' -validExitCodes '0 1223' -silentArgs '/quiet' -file 'C:\ProgramData\chocolatey\lib\pandoc\tools\pandoc-2.1.3-windows.msi' 
2018-06-27 17:46:33,808 3680 [DEBUG] - Running Get-ProcessorBits -compare '32' 
2018-06-27 17:46:33,824 3680 [INFO ] - Installing pandoc...
2018-06-27 17:46:33,824 3680 [INFO ] - 
2018-06-27 17:46:33,879 3680 [DEBUG] - Running Start-ChocolateyProcessAsAdmin -validExitCodes '0 1223' -workingDirectory 'C:\ProgramData\chocolatey\lib\pandoc\tools' -statements '/i "C:\ProgramData\chocolatey\lib\pandoc\tools\pandoc-2.1.3-windows.msi" /quiet ' -exeToRun 'C:\Windows\System32\msiexec.exe' 
2018-06-27 17:46:33,886 3680 [DEBUG] - Test-ProcessAdminRights: returning True
2018-06-27 17:46:33,888 3680 [DEBUG] - Elevating permissions and running ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\pandoc\tools\pandoc-2.1.3-windows.msi" /quiet ]. This may take a while, depending on the statements.
2018-06-27 17:46:34,379 3680 [DEBUG] - Command ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\pandoc\tools\pandoc-2.1.3-windows.msi" /quiet ] exited with '0'.
2018-06-27 17:46:34,379 3680 [DEBUG] - Finishing 'Start-ChocolateyProcessAsAdmin'
2018-06-27 17:46:34,394 3680 [INFO ] - pandoc has been installed.
2018-06-27 17:46:34,394 3680 [INFO ] - 
2018-06-27 17:46:34,410 3680 [INFO ] - VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
2018-06-27 17:46:34,410 3680 [DEBUG] - Running 'Get-UninstallRegistryKey' for 'pandoc' with SoftwareName:'Pandoc *'
2018-06-27 17:46:34,410 3680 [INFO ] - VERBOSE: Retrieving all uninstall registry keys
2018-06-27 17:46:34,660 3680 [DEBUG] - Registry uninstall keys on system: 388
2018-06-27 17:46:34,660 3680 [DEBUG] - Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
2018-06-27 17:46:34,785 3680 [DEBUG] - Found 1 uninstall registry key(s) with SoftwareName:'Pandoc *'
2018-06-27 17:46:34,785 3680 [INFO ] - VERBOSE: Trying Uninstall key property 'InstallLocation'
2018-06-27 17:46:34,801 3680 [INFO ] - VERBOSE: Trying Uninstall key property 'UninstallString'
2018-06-27 17:46:34,801 3680 [INFO ] - VERBOSE: Trying Uninstall key property 'DisplayIcon'
2018-06-27 17:46:34,801 3680 [DEBUG] - Running Get-ProcessorBits -compare '64' 
2018-06-27 17:46:34,801 3680 [INFO ] - VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*
2018-06-27 17:46:34,894 3680 [INFO ] - VERBOSE: Trying native commands on PATH
2018-06-27 17:46:35,351 3680 [ERROR] - ERROR: Cannot bind argument to parameter 'Path' because it is null.
2018-06-27 17:46:35,366 3680 [DEBUG] - Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\pandoc\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
```

Addiotional output of `cinst --verbose --trace --debug -y -f pandoc`:

```
Command ["C:\Windows\System32\msiexec.exe" /i "C:\ProgramData\chocolatey\lib\pandoc\tools\pandoc-2.1.3-windows.msi" /quiet ] exited with '0'.
Finishing 'Start-ChocolateyProcessAsAdmin'
pandoc has been installed.
VERBOSE: Trying local and machine (x32 & x64) Uninstall keys
Running 'Get-UninstallRegistryKey' for 'pandoc' with SoftwareName:'Pandoc *'
VERBOSE: Retrieving all uninstall registry keys
Registry uninstall keys on system: 388
Error handling check: 'Get-ItemProperty' fails if a registry key is encoded incorrectly.
Found 1 uninstall registry key(s) with SoftwareName:'Pandoc *'
VERBOSE: Trying Uninstall key property 'InstallLocation'
VERBOSE: Trying Uninstall key property 'UninstallString'
VERBOSE: Trying Uninstall key property 'DisplayIcon'
Running Get-ProcessorBits -compare '64'
VERBOSE: Trying Program Files with 2 levels depth: C:\Program Files C:\Program Files\*\* C:\Program Files (x86) C:\Program Files (x86)\*\*
VERBOSE: Trying native commands on PATH
ERROR: Cannot bind argument to parameter 'Path' because it is null.
    at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input, Hashtable errorResults, Boolean enumerate)
   at System.Management.Automation.PipelineNode.Execute(Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
   at System.Management.Automation.ParseTreeNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.AssignmentStatementNode.Execute(Array input, Pipe outputPipe, ExecutionContext context)
   at System.Management.Automation.StatementListNode.ExecuteStatement(ParseTreeNode statement, Array input, Pipe outputPipe, ArrayList& resultList, ExecutionContext context)
Built-in PowerShell host called with ['[System.Threading.Thread]::CurrentThread.CurrentCulture = '';[System.Threading.Thread]::CurrentThread.CurrentUICulture = ''; & import-module -name 'C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1'; & 'C:\ProgramData\chocolatey\helpers\chocolateyScriptRunner.ps1' -packageScript 'C:\ProgramData\chocolatey\lib\pandoc\tools\chocolateyInstall.ps1' -installArguments '' -packageParameters '''] exited with '-1'.
```

## My Environment

Windows 7 Pro SP1 (Russian)
chocolatey 0.10.11
chocolatey-core.extension 1.3.3

## Misc

According to same error message maybe related to chocolatey/chocolatey-coreteampackages#873.

**Comment by majkinetor** [comment]
That is strange error. Probably related to "Built-in PowerShell host" or Win 7.

You should try standard powershell and maybe something newer then 2.0.

This is related to chocolatey core extension and not the package.
